import Icon from "./Icon";
export const RECORDING = new Icon(require("../assets/images/record/recording_icon.png"), 20, 14);
// export const RECORD_BUTTON = new Icon(require("../assets/images/record_button.png"), 70, 119);
// export const PLAY_BUTTON = new Icon(require("../assets/images/play_button.png"), 34, 51);
export const PAUSE_BUTTON = new Icon(require("../assets/images/record/resume_button.png"), 34, 51);
export const STOP_BUTTON = new Icon(require("../assets/images/record/stop_button.png"), 22, 22);
export const MUTED_BUTTON = new Icon(require("../assets/images/record/muted_button.png"), 67, 58);
export const UNMUTED_BUTTON = new Icon(require("../assets/images/record/volume_button.png"), 67, 58);
export const TRACK_1 = new Icon(require("../assets/images/track_1.png"), 166, 5);
export const THUMB_1 = new Icon(require("../assets/images/thumb_1.png"), 18, 19);
export const THUMB_2 = new Icon(require("../assets/images/thumb_2.png"), 15, 19);
export const RECORD_BUTTON = new Icon(require("../assets/images/record/record_button.png"), 70, 119);
export const PLAY_BUTTON = new Icon(require("../assets/images/record/play_button.png"), 34, 51);